travis:
  secure:
    BINSTAR_TOKEN: op98qyJqIO3/0HAjFTdBzwY32/dPt28lwkS7U3EDYt+8lXCaZGDGnPdMJIw7p79aU7k8/N69HDkTl8/rfGS9f/89OiNnyvPgeNSLcDPaI010lKJkrkyTE2UALuFLgM+Vht5zZGB+NVELEPoeMvdiwU9HCj25Czg7aqJJRqqt1JpPEyYjsxjQ5wiMYqe6+60MgGOuIQaudVcIQPeB/DgbYfzZGEsAN5DV/S1mOR9OZ1elFH1UNvSsm0O9i+TwMCm+5JVM03aNkUirtrZ2EbATYhmSigWPOnPMuA3yqoZLdz9tVhnqq0uV39ODyNFJyeJWAirThukxRl4GJ+C4yWomG1P17mWEYPbKQJ19/DiaGeiVNLAeAuYfwyBRnQbPcD2Ke36g1jo3j25QmKEfArlL94QnfzMKdP4/qLouVackX5pRRTlnNU3gq3qwWSuY9PnhE+d48flQ0cEk72batk+mWzHeDNymAGWkoR/CXDjCHgaVMAw/ilSY8fFlWOe7bTCk+p5CZE+K45Ep7Of73lTmT8KeWND+Dmt7c1KHe5u3mP/N3eaBgVW+M2rhXjSRvj+O2XAunDHN7/gImG/oo/H+4ewuNhRhPXmV63PaKp6MHHFacq4g2XxiN0R26gwcCNoL8Vx6emB0nTeRCHITk/MDKt0znxgtlLh8pfBv9Xv9FPA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
