travis:
  secure:
    BINSTAR_TOKEN: k0WvkrIdeWXwQWRpVyhfOxvNUwmei6MmvCN+Z2PqiG8ZNBTijGjekZs0ryM1n2g3FEpoe3rHcthmSue0XS8jco8yZzOBdYfLlCosZe2Nee4Dt4alC8s2yb4lYBS68MjIrtsZ91n+0bjVuhzZjwYC8LQzdWxNAhD1d4azxc+VBXkmCvbM273ox2fsxcQAMp6MP0MReh58BvBpquHlhYgnBjvlNpgmZeECTwpuv2G0fkc24AWHZwnciRYNuu9bXdLu9mhjF1RjYmsYYf7VbYXMMuGyPxL4f/HdevD3ChxxX0ZqPxf0iyMJChkb7lFvqJN8MS2YyjRu8Ijd/By5bK2prtx6rTtzFHgMB483CWMqgoUPZZSCUGaMPUCLkbl0rQNG2tP+v+XvIdSQDLTq0XUguCVqKNdFV/y3Jah22u1UrUYv6dLkNxf4CDszQ9tsvuqQ5DnaAUz+Foy8zWtIxWP0WT+kgiEhVgl2hIcnxVCeGR7dSeB0Qa4wsb9Tdav0GCbEKzYLta2HiFKw10dJ9ThHiTZ9C5OVwpl17p9Rpb016hIh868jT+8vUBO0XoIUjpgdcPcYQVDtrMeoQshPUKUDuzFzNhLUen8i4bCrYr+WLcD32ZKa75HSqr47l8bKq/8Wa+xYk9zDPrmXsqEYILkb+tTrTN9ensMzKSKC8kk0cEo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
